from functions import *

def contruct_embed_prices1(response_BTC,response_ETH,response_XRP,response_LINK,response_ALGO,response_COS,response_GRT,response_BTC_1hrchng,response_ETH_1hrchng,response_XRP_1hrchng,response_LINK_1hrchng,response_ALGO_1hrchng,response_COS_1hrchng,response_GRT_1hrchng,response_BTC_24hrchng,response_ETH_24hrchng,response_XRP_24hrchng,response_LINK_24hrchng,response_ALGO_24hrchng,response_COS_24hrchng,response_SOL,response_SOL_1hrchng,response_SOL_24hrchng,response_GRT_24hrchng):
    embed=discord.Embed(title="Crypto Prices", description="Gets updated crypto prices for our tracked cryptos!", color=0x0000ff)
    embed.set_thumbnail(url="https://i.imgur.com/yo9flkI.png")
    embed.add_field(name="Bitcoin:", value="$"+str(response_BTC), inline=True)
    embed.add_field(name="BTC[1hr]:", value=format(response_BTC_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="BTC[24hr]:", value=format(response_BTC_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Ethereum:", value="$"+str(response_ETH), inline=True)
    embed.add_field(name="Eth[1hr]:", value=format(response_ETH_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Eth[24hr]:", value=format(response_ETH_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Ripple:", value="$"+str(response_XRP), inline=True)
    embed.add_field(name="XRP[1hr]:", value=format(response_XRP_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="XRP[24hr]:", value=format(response_XRP_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="ChainLink:", value="$"+str(response_LINK), inline=True)
    embed.add_field(name="Link[1hr]:", value=format(response_LINK_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Link[24hr]:", value=format(response_LINK_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Algorand:", value="$"+str(response_ALGO), inline=True)
    embed.add_field(name="Algo[1hr]:", value=format(response_ALGO_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Algo[24hr]:", value=format(response_ALGO_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Cosmos:", value="$"+str(response_COS), inline=True)
    embed.add_field(name="Atom[1hr]:", value=format(response_COS_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Atom[24hr]:", value=format(response_COS_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Solana:", value="$"+str(response_SOL), inline=True)
    embed.add_field(name="Sol[1hr]:", value=format(response_SOL_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Sol[24hr]:", value=format(response_SOL_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="The Graph:", value="$"+str(response_GRT), inline=True)
    embed.add_field(name="GRT[1hr]:", value=format(response_GRT_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="GRT[24hr]:", value=format(response_GRT_24hrchng,'.4f')+"%", inline=True)
    return embed

def contruct_embed_prices2(response_MATIC,response_MATIC_1hrchng,response_MATIC_24hrchng,response_REN,response_LTC,response_ADA,response_AXS,response_BAT,response_DOT,response_SHIB,response_REN_1hrchng,response_LTC_1hrchng,response_ADA_1hrchng,response_AXS_1hrchng,response_BAT_1hrchng,response_DOT_1hrchng,response_SHIB_1hrchng,response_REN_24hrchng,response_LTC_24hrchng,response_ADA_24hrchng,response_AXS_24hrchng,response_BAT_24hrchng,response_DOT_24hrchng,response_SHIB_24hrchng):
    embed=discord.Embed(title="Crypto Prices", description="Gets updated crypto prices for our tracked cryptos!", color=0x0000ff)
    embed.set_thumbnail(url="https://i.imgur.com/yo9flkI.png")
    embed.add_field(name="Ren:", value="$"+str(response_REN), inline=True)
    embed.add_field(name="Ren[1hr]:", value=format(response_REN_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Ren[24hr]:", value=format(response_REN_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Polygon:", value="$"+str(response_MATIC), inline=True)
    embed.add_field(name="MATIC[1hr]:", value=format(response_MATIC_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="MATIC[24hr]:", value=format(response_MATIC_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="LiteCoin:", value="$"+str(response_LTC), inline=True)
    embed.add_field(name="LTC[1hr]:", value=format(response_LTC_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="LTC[24hr]:", value=format(response_LTC_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Cardano:", value="$"+str(response_ADA), inline=True)
    embed.add_field(name="ADA[1hr]:", value=format(response_ADA_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="ADA[24hr]:", value=format(response_ADA_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Axie Infinity:", value="$"+str(response_AXS), inline=True)
    embed.add_field(name="AXS[1hr]:", value=format(response_AXS_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="AXS[24hr]:", value=format(response_AXS_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Basic Attention:", value="$"+str(response_BAT), inline=True)
    embed.add_field(name="BAT[1hr]:", value=format(response_BAT_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="BAT[24hr]:", value=format(response_BAT_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Polkadot:", value="$"+str(response_DOT), inline=True)
    embed.add_field(name="DOT[1hr]:", value=format(response_DOT_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="DOT[24hr]:", value=format(response_DOT_24hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="Shiba-inu:", value="$"+str(response_SHIB), inline=True)
    embed.add_field(name="SHIB[1hr]:", value=format(response_SHIB_1hrchng,'.4f')+"%", inline=True)
    embed.add_field(name="SHIB[24hr]:", value=format(response_SHIB_24hrchng,'.4f')+"%", inline=True)
    return embed

def contruct_embed_stockprices(tsla_Stock_Price,spy_Stock_Price,amd_Stock_Price,gme_Stock_Price,amc_Stock_Price,CLNE_Stock_Price):
    embed=discord.Embed(title="Stock Prices", description="What the close price of the most recent minute is", color=0x0000ff)
    embed.set_thumbnail(url="https://i.imgur.com/xvGJJod.png")
    embed.add_field(name="TSLA:", value="$" + str(tsla_Stock_Price), inline=True)
    embed.add_field(name="SPY:", value="$" + str(spy_Stock_Price), inline=True)
    embed.add_field(name="AMD:", value="$" + str(amd_Stock_Price), inline=True)
    embed.add_field(name="GME:", value="$" + str(gme_Stock_Price), inline=True)
    embed.add_field(name="AMC:", value="$" + str(amc_Stock_Price), inline=True)
    embed.add_field(name="CLNE:", value="$" + str(CLNE_Stock_Price), inline=True)
    return embed
